## Example commands
#  run DT on walker2d
python experiment.py --env walker2d --dataset medium --model_type dt --seed 666    --outdir "checkpoints/dt_kmeans_medium_positions_walker2d_paper_666" 
python experiment.py --env walker2d --dataset medium --model_type dt --seed 42  --outdir "checkpoints/dt_kmeans_medium_positions_walker2d_paper_42"  
python experiment.py --env walker2d --dataset medium --model_type dt --seed 1024  --outdir "checkpoints/dt_kmeans_medium_positions_walker2d_paper_1024"  

# run ChibiT on hopper medium-expert
python experiment.py --env hopper --dataset medium-expert --model_type dt --seed 666  --pretrained_lm chibiT  --outdir "checkpoints/cibiT_kmeans_medium_expert_positions_hopper_paper_666" --extend_positions --gpt_kmeans 1000 --kmeans_cache "kmeans_cache/chibiv2_lm_1000.pt" --gpt_kmeans_const 0.1  --dropout 0.2 --share_input_output_proj
python experiment.py --env hopper --dataset medium-expert --model_type dt --seed 42  --pretrained_lm chibiT  --outdir "checkpoints/cibiT_kmeans_medium_expert_positions_hopper_paper_42" --extend_positions --gpt_kmeans 1000 --kmeans_cache "kmeans_cache/chibiv2_lm_1000.pt" --gpt_kmeans_const 0.1  --dropout 0.2 --share_input_output_proj
python experiment.py --env hopper --dataset medium-expert --model_type dt --seed 1024  --pretrained_lm chibiT  --outdir "checkpoints/cibiT_kmeans_medium_expert_positions_hopper_paper_1024" --extend_positions --gpt_kmeans 1000 --kmeans_cache "kmeans_cache/chibiv2_lm_1000.pt" --gpt_kmeans_const 0.1  --dropout 0.2 --share_input_output_proj

# run GPT2 on reacher2d medium
python experiment.py --env reacher2d --dataset medium --model_type dt --seed 1024 --pretrained_lm gpt2  --outdir "checkpoints/gpt2_kmeans_medium_positions_reacher2d_1024" --extend_positions --gpt_kmeans 1000 --kmeans_cache "kmeans_cache/gpt2_lm_1000.pt" --gpt_kmeans_const 0.1 --dropout 0.2 --share_input_output_proj
python experiment.py --env reacher2d --dataset medium --model_type dt --seed 666  --pretrained_lm gpt2  --outdir "checkpoints/gpt2_kmeans_medium_positions_reacher2d_666" --extend_positions --gpt_kmeans 1000 --kmeans_cache "kmeans_cache/gpt2_lm_1000.pt" --gpt_kmeans_const 0.1  --dropout 0.2 --share_input_output_proj
python experiment.py --env reacher2d --dataset medium --model_type dt --seed 42  --pretrained_lm gpt2  --outdir "checkpoints/gpt2_kmeans_medium_positions_reacher2d_42" --extend_positions --gpt_kmeans 1000 --kmeans_cache "kmeans_cache/gpt2_lm_1000.pt" --gpt_kmeans_const 0.1  --dropout 0.2 --share_input_output_proj

# run perturbation per layer on hopper medium
python experiment.py --env hopper --dataset medium --model_type dt --seed 666  --pretrained_lm chibiT  --outdir "checkpoints/cibiT_kmeans_medium_positions_hopper_perturb_8e0_666" --extend_positions --gpt_kmeans 1000 --kmeans_cache "kmeans_cache/chibiv2_lm_1000.pt" --gpt_kmeans_const 0.1  --dropout 0.2 --share_input_output_proj --perturb --perturb_per_layer 8e0
python experiment.py --env hopper --dataset medium --model_type dt --seed 42  --pretrained_lm chibiT  --outdir "checkpoints/cibiT_kmeans_medium_positions_hopper_perturb_8e0_42" --extend_positions --gpt_kmeans 1000 --kmeans_cache "kmeans_cache/chibiv2_lm_1000.pt" --gpt_kmeans_const 0.1  --dropout 0.2 --share_input_output_proj --perturb --perturb_per_layer 8e0
python experiment.py --env hopper --dataset medium --model_type dt --seed 1024  --pretrained_lm chibiT  --outdir "checkpoints/cibiT_kmeans_medium_positions_hopper_perturb_8e0_1024" --extend_positions --gpt_kmeans 1000 --kmeans_cache "kmeans_cache/chibiv2_lm_1000.pt" --gpt_kmeans_const 0.1  --dropout 0.2 --share_input_output_proj --perturb --perturb_per_layer 8e0

# run perturbation per layer on hopper medium with only mlp layers
python experiment.py --env hopper --dataset medium --model_type dt --seed 666  --pretrained_lm chibiT  --outdir "checkpoints/cibiT_kmeans_medium_positions_hopper_perturb_new_mlp_8e0_rerun_666" --extend_positions --gpt_kmeans 1000 --kmeans_cache "kmeans_cache/chibiv2_lm_1000.pt" --gpt_kmeans_const 0.1  --dropout 0.2 --share_input_output_proj --perturb --perturb_per_layer 8e0 --perturb_transformer_only --perturb_mlp_only
python experiment.py --env hopper --dataset medium --model_type dt --seed 42  --pretrained_lm chibiT  --outdir "checkpoints/cibiT_kmeans_medium_positions_hopper_perturb_new_mlp_8e0_rerun_42" --extend_positions --gpt_kmeans 1000 --kmeans_cache "kmeans_cache/chibiv2_lm_1000.pt" --gpt_kmeans_const 0.1  --dropout 0.2 --share_input_output_proj --perturb --perturb_per_layer 8e0 --perturb_transformer_only --perturb_mlp_only
python experiment.py --env hopper --dataset medium --model_type dt --seed 1024  --pretrained_lm chibiT  --outdir "checkpoints/cibiT_kmeans_medium_positions_hopper_perturb_new_mlp_8e0_rerun_1024" --extend_positions --gpt_kmeans 1000 --kmeans_cache "kmeans_cache/chibiv2_lm_1000.pt" --gpt_kmeans_const 0.1  --dropout 0.2 --share_input_output_proj --perturb --perturb_per_layer 8e0 --perturb_transformer_only --perturb_mlp_only
##cp -r /scratch/zw2374/public/faiss_db/{mpnet_distilgpt2_not_concat,mpnet_gpt2_concat_new,mpnet_gpt2_not_concat,mpnet_gpt2_not_concat_1e-5,mpnet_gpt2_not_concat_rerun,multil6_alll12_not_concat,multil6_alll12_not_concat_200e_128,multil6_fair_baseline,multil6_minil12_not_concat_200e_128,minilm_l12_baseline,minilm_l12_baseline_eval,minilm_l6_baseline_eval,minil12_fair_baseline,minil6_fair_baseline,gpt2_fair_baseline,fast_processed_data_allminil12_final,distilgpt2_baseline,distilroberta_baseline,distilroberta_distilroberta_not_concat,distilroberta_roberta_not_concat_1e-5,distilbert_distilbert_not_concat,distilbert_distilgpt2,distilbert_distilgpt2_not_concat,distilbert_distilroberta_not_concat,distilbert_gpt2_not_concat_1e-5,distilbert_roberta_not_concat_1e-5,distilbert_bert_not_concat_1e-5,distilbert_baseline,bert_fair_baseline,allminil12_allminilml12,allmini_l12_baseline,allminil12_minilml12,allminil16_allminilml12,allminil16_minilml12,allminil16_minilml12_real,allmini_l6_baseline,alll12_alll12_not_concat_200e_128,alll12_fair_baseline,alll12_minil12_not_concat_200e_128,alll6_alll12_not_concat_200e_128,alll6_alll6_not_concat_200e_128,alll6_fair_baseline,alll6_minil12_not_concat_200e_128,alll6_minil6_not_concat_200e_128} /vast/zw2374/faiss_db 